 enum class SlidanetRequestType { Connect,
                                 ConnectContent,
                                 EditContent,
                                 CommitContentEditing,
                                 CancelContentEditing,
                                 SetContentShareStyle,
                                 SetMoveContent,
                                 GiveContent,
                                 TakeContent,
                                 SetContentVisibilityPreference,
                                 PlayContent,
                                 PauseContent,
                                 SetVideoStartTime,
                                 DisconnectContent,
                                 DisconnectAllContent,
                                 Disconnect,
                                 SlidanetUpdate,
                                 SetContentFilter,
                                 HideContent,
                                 UnhideContent,
                                 DoneEditContent,
                                 MaxValue }

enum class SlidanetSharingStyleType { SlideLeftAndRight,
                                      SlideUpAndDown,
                                      SlideAllDirections,
                                      PeekDefine,
                                      PeekSlide,
                                      PixDefine,
                                      PixSlide,
                                      MaxValue }

 enum class SlidanetActionType { AnimateIntoView,
                                 AnimateOutOfView
 }

enum class SlidanetVisibilityPreferenceType { RequestLess,
                                              Neutral,
                                              RequestMore,
                                              MaxValue }

 enum class SlidanetContentFilterType { Default,
                                        MaxValue }

internal enum class SlidanetMessageType { AuthenticateConnectionRequest,
                                          AuthenticateConnectionResponse,
                                          ConnectContentRequest,
                                          ConnectContentResponse,
                                          UpdateContentContextRequest,
                                          MoveContentRequest,
                                          MoveContentResponse,
                                          SetContentVisibilityPreferenceRequest,
                                          SetContentVisibilityPreferenceResponse,
                                          GiveContentRequest,
                                          GiveContentResponse,
                                          TakeContentRequest,
                                          TakeContentResponse,
                                          MoreContentRequest,
                                          MoreContentResponse,
                                          LessContentRequest,
                                          LessContentResponse,
                                          SetContentShareModeRequest,
                                          SetContentShareModeResponse,
                                          SetContentFilterRequest,
                                          SetContentFilterResponse,
                                          DisconnectContentRequest,
                                          DisconnectContentResponse,
                                          DisconnectAllContentRequest,
                                          DisconnectAllContentResponse,
                                          TakeNotificationRequest,
                                          VisibilityNotificationRequest,
                                          SetHideContentRequest,
                                          SetHideContentResponse,
                                          DisconnectRequest,
                                          DisconnectResponse,
                                          ViewerLeftNotificationRequest,
                                          ViewerJoinedNotificationRequest,
                                          MaxValue }

enum class SlidanetResponseType { Ok,
                                  Undefined,
                                  RequestSubmitted,
                                  ApplicationNameContainsNonASCIICharacters,
                                  ApplicationNameTooLong,
                                  ApplicationPasswordTooLong,
                                  SlidaNameTooLong,
                                  ApplicationPasswordContainsNonASCIICharacters,
                                  ApplicationPasswordLengthGreaterThan32,
                                  SlidaNameContainsNonASCIICharacters,
                                  SlidaNameLengthGreaterThan32,
                                  BadAppContentPath,
                                  InvalidIpAddressFormat,
                                  InvalidPortNumber,
                                  ConnectionAuthenticated,
                                  DisconnectedFromAllContent,
                                  AppContentFileNotFound,
                                  UnableToDecodeAppContentFile,
                                  UnableToLoadInitialVideoFrame,
                                  NotConnectedToSlidanet,
                                  InvalidSlidanetContentAddress,
                                  InvalidAppVideoStartTime,
                                  AppContentConnectedToSlidanetAddress,
                                  SlidanetContentAddressNotFound,
                                  InvalidSlidanetContentAddressForPlatform,
                                  Disconnected,
                                  InternalErrorOccurred,
                                  OutstandingRequestExists,
                                  UnsupportedContentType,
                                  InvalidApplicationPassword,
                                  AuthenticationFailed,
                                  ConnectedToContent,
                                  DisconnectedFromContent,
                                  ContentAddressNotInApplication,
                                  ContentAddressNotFound,
                                  ContentGiven,
                                  ContentTaken,
                                  VisibilityPreferenceSet,
                                  ShareModeDefinitionSet,
                                  HideSet,
                                  HideUnset,
                                  AlreadyConnectedToSlidanet,
                                  AlreadyConnectedToContent,
                                  NotConnectedToContent,
                                  ScreenWidthMustBeGreaterThanZero,
                                  ScreenHeightMustBeGreaterThanZero,
                                  ScreenHeightMustBeGreaterThanWidth,
                                  EditingContent,
                                  CommittedContentEdits,
                                  CancelledContentEdits,
                                  DoneEditingContentAddress,
                                  NotEditingContent,
                                  EditingInProgress,
                                  AddressNotMatchingEditedContent,
                                  NotContentAddressOwner,
                                  UpdatesImmediatelyDistributed,
                                  CancelNotAllowedInThisState,
                                  InvalidSlideParameters,
                                  InvalidPeekParameters,
                                  InvalidPixParameters,
                                  GiveAlreadyEnabled,
                                  GiveNotEnabled,
                                  ContentAlreadyTakenBack,
                                  AlreadyContentAddressOwner,
                                  PreferenceMatchesCurrent,
                                  ContentAlreadyFrozen,
                                  VideoContentTypeRequired,
                                  ContentFilterAlreadySet,
                                  ContentAlreadyHidden,
                                  ContentNotHidden,
                                  ContentHidden,
                                  ContentUnhidden,
                                  FilterSet,
                                  AlreadyInSlideMode,
                                  AlreadyInPeekDefineMode,
                                  AlreadyInPeekSlideMode,
                                  AlreadyInPixDefineMode,
                                  AlreadyInPixSlideMode,
                                  MaxValue }

enum class SlidanetContentType { Image,
                                 StaticVideo,
                                 StreamedVideo,
                                 MaxValue }

internal enum class SlidanetEditingStateType { Active, InActive }

 internal enum class SlidanetEditingInitiatorType { DoubleTap, LocalShareStyleUpdate, LocalEditing }

internal enum class SlidanetLoggingRequestType { Move }

