import android.graphics.Color

internal object Constants {

    internal const val majorVersion = 1
    internal const val minorVersion = 0
    internal const val patchNumber = 0
    internal const val networkMessageSizeLength: Int = 10
    internal const val networkMessageTypeLength: Int = 5
    internal const val networkMessageHeaderLength = networkMessageSizeLength + networkMessageTypeLength
    const val floatWidth: Int = 10
    const val integerWidth: Int = 10
    const val shortWidth: Int = 5
    const val nameWidth = 2
    const val flagWidth = 1
    const val uuidWidth = 32
    const val defaultFontSize = 14.0F
    const val defaultPixelWidth = 30
    const val platformName = "platform_name"
    const val platformId = "platform_id"
    const val platformPassword = "platform_password"
    const val slidanetUserIdLiteral = "slidanet_user_id"
    const val slidanetContentAddressLiteral = "slidanet_content_address"
    const val requestData = "request_data"
    const val responseCode = "response_code"
    const val responseData = "response_data"
    const val ipAddressLiteral = "ip_address"
    const val ipPortLiteral = "ip_port"
    const val keystorePassword = "slidanet"
    const val responseCodeLiteral = "response_code"
    const val successLiteral = "success"
    const val contentTypeLiteral = "content_type"
    const val videoStartTimeLiteral = "video_start_time"
    const val contentPathLiteral = "app_content_path"
    const val requestInfoLiteral = "request_info"
    const val preferenceLiteral = "preference"
    const val defaultSlideEditingScale = 3.0F
    const val noRotation = 0
    const val sizeOfFloat = 4
    const val videoTimeoutMicroseconds = 10000L
    const val SlidanetViewTag = "SlidanetView: "
    const val SlidanetVideoPlayerTag = "SlidanetVideoPlayer: "
    const val stateStop = 0
    const val statePrepared = 1
    const val statePlaying = 2
    const val statePaused = 3
    const val reqNon = 0
    const val reqPrepare = 1
    const val reqStart = 2
    const val reqSeek = 3
    const val reqStop = 4
    const val reqPause = 5
    const val reqResume = 6
    const val reqQuit = 9
    const val rotateLeft = 90
    const val rotateUpsideDown = 180
    const val rotateRight = 270
    val supportImageFileTypes = arrayOf("jpeg", "png")
    val supportVideoFileTypes = arrayOf("mp4", "wav")
    const val defaultBorderColor = Color.RED
    const val defaultBorderWidth = 5
    const val share_style = "share_style"
    const val peek = "peek"
    const val pix = "pix"
    const val slide = "slide"
    const val defaultShaderName = "default"
    const val doubleTapInterval = 700
    const val pointerDownTimeInterval = 500
    const val maskColorOwnerAlpha = .3f
    const val maskColorFollowerAlpha = 1f
}